# If you are doing the labs, this file is not for you.
# This file is used for repository maintenance.
[tool.black]
line-length = 80
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 80

[tool.pylint.messages_control]
disable = [
    # Rely on isort and black to handle the imports
    "wrong-import-order",
    "ungrouped-imports",
    # We should gradually fix these and remove these temporary disables.
    "missing-function-docstring",
    "missing-module-docstring",
    "missing-class-docstring",
]


[tool.pylint.similarities]
ignore-docstrings = "yes"
min-similarity-lines = 8

[tool.pylint.main]

ignore = ["implementations"]
ignore-patterns = ["test_.*py"]
init-hook="import sys; sys.path.append('./portfolio_manager'); sys.path.append('./rabbit_mq')"

